/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cwru.selab.cf;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void testConstructDriver() {
    new Driver();
  }
}
